[package]
name = "steward"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["crates/simulation","crates/util"]

[workspace.dependencies]
bumpalo = { version = "3", features = ["collections"] }
macroquad = "0.4.4"
egui-macroquad = "0.17"
egui = "0.31"
slotmap = "1"
string-interner = "0.19"
simulation = { path = "crates/simulation" }
util = { path = "crates/util" }

[dependencies]
bumpalo = { workspace = true }
macroquad = { workspace = true }
egui-macroquad = { workspace = true }
egui = { workspace = true }
slotmap = { workspace = true }
simulation = { workspace = true }
util = { workspace = true }

